#! /usr/bin/env python
import os
import sys

# Run arduino-keywords
os.system("mkdir keywords")
os.system("~/.local/bin/arduino-keywords src --output ../keywords > /dev/null 2>&1")
os.system("sed -i '/operator=/d' keywords/keywords.txt > /dev/null 2>&1")

# Get a set of the lines from a file
# Using a set to ignore order (as arduino-keyword search order is system dependent)
def get_keywords(filename):
    results = set()
    with open(filename, "r") as f:
        for line in f:
            results.add(line)
    return results

# Read both keywords.txt
existing_set = get_keywords("keywords.txt")
new_set = get_keywords("keywords/keywords.txt")

# Are they the same?
if existing_set != new_set:
    print("keywords.txt is not correct. Please run build.sh to generate keywords.txt!")
    print("Differences:")
    for keyword in existing_set.symmetric_difference(new_set):
        print(keyword)
    sys.exit(1)